Rhys-T: b397a0eecb -> 3d06e2199b

diff --git a/repos/Rhys-T/.github/workflows/build.yml b/repos/Rhys-T/.github/workflows/build.yml
--- a/repos/Rhys-T/.github/workflows/build.yml
+++ b/repos/Rhys-T/.github/workflows/build.yml
@@ -45,22 +45,22 @@ jobs:
             
             [
               "Lnx x64/ubuntu-latest",
-              "Lnx A64/ubuntu-24.04-arm",
-              "Mac x64/macos-13",
-              "Mac A64/macos-latest",
+              # "Lnx A64/ubuntu-24.04-arm",
+              # "Mac x64/macos-13",
+              # "Mac A64/macos-latest",
             empty] as $runners |
             
             [
               "nixpkgs-unstable",
-              "nixos-unstable",
-              "nixos-\(($stable, $oldStable) | select(. != null))",
+              # "nixos-unstable",
+              # "nixos-\(($stable, $oldStable) | select(. != null))",
             empty] as $nixpkgss |
             
             [
               "base",
-              "mame",
-              "hbmame",
-              "qemu-screamer",
+              # "mame",
+              # "hbmame",
+              # "qemu-screamer",
             empty] as $subsets |
             
             {include: [
@@ -224,6 +224,9 @@ jobs:
       id: build
       run: |
         set -x
+        ls -al /tmp/buildFailures || true
+        [[ -d /tmp/buildFailures ]] && echo '[[ -d /tmp/buildFailures ]]' || echo '[[ ! -d /tmp/buildFailures ]]'
+        exit 1
         mkdir -p /tmp/tempFlake/conf
         tempFlake="$(realpath /tmp/tempFlake)"
         echo -En '${{ matrix.subset }}' > "$tempFlake/conf/ciSubsetName"
