colinsane: init at 24ff548453 (https://github.com/nix-community/nur-combined/commit/78d05e81ec)

diff --git a/repos/colinsane/hosts/modules/services/rsync-net/sane-backup-rsync-net b/repos/colinsane/hosts/modules/services/rsync-net/sane-backup-rsync-net
--- a/repos/colinsane/hosts/modules/services/rsync-net/sane-backup-rsync-net
+++ b/repos/colinsane/hosts/modules/services/rsync-net/sane-backup-rsync-net
@@ -6,35 +6,80 @@
 # for setup, see: <https://www.rsync.net/resources/howto/ssh_keys.html>
 # - requires my pubkey to be copied to .ssh/authorized_keys on the remote.
 
-set -xeu
+set -eu
 
-# secret should include RN_USER
-source /run/secrets/rsync-net-env
-RN_ID=/run/secrets/rsync-net-id_ed25519
-PREFIX=$(hostname)
+usage() {
+  echo 'sane-backup-rsync-net DIRECTORY...'
+  echo
+  echo "sync's each DIRECTORY with its counterpart stored on my rsync.net account"
+  echo
+  echo "on success, the remote directory will be an exact logical replica oc the local directory"
+  echo "that is, files present under the remote directory but NOT present under the local directory are deleted"
+  echo
+  echo "exits 1 if any directory fails to sync"
+}
 
-test -n "$PREFIX" && test -n "$RN_USER" && test -f "$RN_ID"
+dirs=()
+parseArgs() {
+  while [ "$#" -ne 0 ]; do
+    local arg=$1
+    shift
+    if (( ${#dirs[@]} )); then
+      # all remaining arguments are to be forwarded to the subcommand
+      dirs+=("$arg")
+    else
+      case $arg in
+        (--help)
+          usage
+          exit 0
+          ;;
+        (*)
+          dirs=("$arg")
+          ;;
+      esac
+    fi
+  done
 
-rc=
-for dir in "$@"; do
-  if [[ "$dir" != */ ]]; then
-    dir="$dir/"
+  if [ -z "$dirs" ]; then
+    usage
+    exit 1
   fi
-  remote_dir="$RN_USER@$RN_USER.rsync.net:$PREFIX$dir"
+}
 
-  now=$(date '+%s')
-  echo "syncing '$dir' to '$remote_dir'"
-  echo "$now" > "$dir"/zzz-rsync-net/last-attempted
-  # N.B.: manual flags instead of `-a -> -rlptgoD` because device files have a max path length which is too restricted
-  # TODO: add `sane-vpn do unmetered --`, after fixing pasta/sane-vpn to preserve capabilities + not create a new user namespace unconditionally.
-  # until then, don't run over cellular!
-  if rsync --exclude="$RN_ID" -e "ssh -i $RN_ID" --mkpath -rlptgov --delete "$dir" "$remote_dir"; then
-    echo "$now" > "$dir"/zzz-rsync-net/last-completed
-    rc=0$rc
-  else
-    rc=1
-    echo "FAILED TO BACKUP $dir"
-  fi
-done
+main() {
+  # secret should include RN_USER
+  source /run/secrets/rsync-net-env
+  local RN_ID=/run/secrets/rsync-net-id_ed25519
+  local PREFIX=$(hostname)
 
-test -n "$rc" && exit $rc
+  test -n "$PREFIX" && test -n "$RN_USER" && test -f "$RN_ID"
+
+  local rc=
+  for dir in "$@"; do
+    if [[ "$dir" != */ ]]; then
+      dir="$dir/"
+    fi
+    local remote_dir="$RN_USER@$RN_USER.rsync.net:$PREFIX$dir"
+
+    local now=$(date '+%s')
+    echo "syncing '$dir' to '$remote_dir'"
+    echo "$now" > "$dir"/zzz-rsync-net/last-attempted
+    # N.B.: manual flags instead of `-a -> -rlptgoD` because device files have a max path length which is too restricted
+    # TODO: add `sane-vpn do unmetered --`, after fixing pasta/sane-vpn to preserve capabilities + not create a new user namespace unconditionally.
+    # until then, don't run over cellular!
+    if rsync --exclude="$RN_ID" -e "ssh -i $RN_ID" --mkpath -rlptgov --delete "$dir" "$remote_dir"; then
+      echo "$now" > "$dir"/zzz-rsync-net/last-completed
+      rc=0$rc
+    else
+      rc=1
+      echo "FAILED TO BACKUP $dir"
+    fi
+  done
+
+  test -n "$rc" && exit $rc
+}
+
+parseArgs "$@"
+
+set -x
+main "${dirs[@]}"
diff --git a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-deadlines b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-deadlines
--- a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-deadlines
+++ b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-deadlines
@@ -19,34 +19,61 @@
 # configurables:
 var deadlines = "$[ENV.HOME]/knowledge/planner/deadlines.tsv"
 
-if ! test -f "$deadlines" {
-  echo "WARNING: $deadlines sane-deadlines file not found"
-  exit 1
+proc usage {
+  echo "sane-deadlines:"
+  echo "  print any upcoming deadlines from $deadlines"
 }
 
-var now=$(date +%s)
-for line in ($(cat "$deadlines") => split(u'\n')) {
-  if (line === "" or line => startsWith("#")) {
-    # ignore comments
-    continue
+func parseArgs(args) {
+  for arg in (args) {
+    case (arg) {
+      ("--help") {
+        usage
+        exit 0
+      }
+      (else) {
+        usage
+        exit 1
+      }
+    }
+  }
+}
+
+proc main {
+  if ! test -f "$deadlines" {
+    echo "WARNING: $deadlines sane-deadlines file not found"
+    exit 1
   }
 
-  # parse normal line
-  var deadline_field=$(echo "$line" | cut -f 1)
-  var threshold_field=$(echo "$line" | cut -f 2)
-  var description_field=$(echo "$line" | cut -f 3)
+  var now=$(date +%s)
+  for line in ($(cat "$deadlines") => split(u'\n')) {
+    if (line === "" or line => startsWith("#")) {
+      # ignore comments
+      continue
+    }
 
-  # normalize dates into seconds since unix epoch
-  var deadline=$(date -d "$deadline_field" +%s)
-  var threshold=$(echo "$threshold_field" | sed 's/d/day /g')
-  var birthtime=$(date -d "$deadline_field - $threshold" +%s)
+    # parse normal line
+    var deadline_field=$(echo "$line" | cut -f 1)
+    var threshold_field=$(echo "$line" | cut -f 2)
+    var description_field=$(echo "$line" | cut -f 3)
 
-  # show the event iff it's near
-  # 86400 = 24*60*60 = # of seconds in a day
-  # 10080 = 24*60*7 = # of seconds between UTC and UTC-7
-  # 11520 = 24*60*8 = # of seconds between UTC and UTC-8
-  if (now >= birthtime) {
-    var days_until = int((deadline - now + 86399) / 86400)
-    echo "in $days_until day(s): $description_field"
+    # normalize dates into seconds since unix epoch
+    var deadline=$(date -d "$deadline_field" +%s)
+    var threshold=$(echo "$threshold_field" | sed 's/d/day /g')
+    var birthtime=$(date -d "$deadline_field - $threshold" +%s)
+
+    # show the event iff it's near
+    # 86400 = 24*60*60 = # of seconds in a day
+    # 10080 = 24*60*7 = # of seconds between UTC and UTC-7
+    # 11520 = 24*60*8 = # of seconds between UTC and UTC-8
+    if (now >= birthtime) {
+      var days_until = int((deadline - now + 86399) / 86400)
+      echo "in $days_until day(s): $description_field"
+    }
   }
+}
+
+if is-main {
+  call parseArgs(ARGV)
+  main
 }
diff --git a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock
--- a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock
+++ b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock
@@ -3,19 +3,46 @@
 
 umask 027
 
-if ! systemctl is-active private-storage.target > /dev/null; then
-  echo "unable to access encrypted data store."
-  echo "unlock it now or cancel with Ctrl+C."
-fi
+usage() {
+  echo "sane-private-unlock:"
+  echo "  unlock the user's private data store (roughly equivalent to an encyrpted home directory)"
+  echo "  or does nothing if already unlocked."
+}
 
-while ! systemctl is-active private-storage.target > /dev/null; do
-  # see: <https://stackoverflow.com/a/2654096>
-  IFS= read -s -r -p "password: " line
-  echo
-  if [[ "$?" -eq 0 && -n "$line" ]]; then
-    echo -n "$line" > /run/gocryptfs/private.key
-    # give time for the store to be unlocked
-    timeout 3s systemctl start private-storage.target
+parseArgs() {
+  while [ $# -ne 0 ]; do
+    local arg="$1"
+    shift
+    case "$arg" in
+      (--help)
+        usage
+        exit 0
+        ;;
+      (*)
+        usage
+        exit 1
+        ;;
+    esac
+  done
+}
+
+main() {
+  if ! systemctl is-active private-storage.target > /dev/null; then
+    echo "unable to access encrypted data store."
+    echo "unlock it now or cancel with Ctrl+C."
   fi
-done
 
+  while ! systemctl is-active private-storage.target > /dev/null; do
+    # see: <https://stackoverflow.com/a/2654096>
+    IFS= read -s -r -p "password: " line
+    echo
+    if [[ "$?" -eq 0 && -n "$line" ]]; then
+      echo -n "$line" > /run/gocryptfs/private.key
+      # give time for the store to be unlocked
+      timeout 3s systemctl start private-storage.target
+    fi
+  done
+}
+
+parseArgs "$@"
+main
diff --git a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock-remote b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock-remote
--- a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock-remote
+++ b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock-remote
@@ -6,14 +6,48 @@
 
 set -eu
 
-host=$1
-passwd=$(sane-secrets-dump --field password "$host")
+usage() {
+  echo "sane-private-unlock-remote HOST"
+  echo "  ssh's into HOST and unlocks its encrypted data store (e.g. encrypted home directory)"
+  echo "  this is non-interactive, and only works so long as the machine running this script"
+  echo "  has HOST's key in its own keyring"
+}
 
-if [ -z "$passwd" ]; then
-  echo "failed to decode password" | tee /dev/stderr
-  exit 1
-fi
+host=
+parseArgs() {
+  while [ "$#" -ne 0 ]; do
+    local arg=$1
+    shift
+    case $arg in
+      (--help)
+        usage
+        exit 0
+        ;;
+      (*)
+        if [ -z "$host" ]; then
+          host=$arg
+        else
+          usage
+          exit 1
+        fi
+        ;;
+    esac
+  done
+}
 
-echo "attempting to mount private store on $host"
-echo "$passwd" | ssh "$host" 'if ! test -f /mnt/persist/private/init; then cat /dev/stdin > /run/gocryptfs/private.key; fi'
-echo "mount succeeded"
+main() {
+  local host="$1"
+  local passwd=$(sane-secrets-dump --field password "$host")
+
+  if [ -z "$passwd" ]; then
+    echo "failed to decode password" | tee /dev/stderr
+    exit 1
+  fi
+
+  echo "attempting to mount private store on $host"
+  echo "$passwd" | timeout 30 ssh "$host" 'if ! test -f /mnt/persist/private/init; then cat /dev/stdin > /run/gocryptfs/private.key; fi'
+  echo "mount succeeded"
+}
+
+parseArgs "$@"
+main "$host"
diff --git a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-sudo-redirect b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-sudo-redirect
--- a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-sudo-redirect
+++ b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-sudo-redirect
@@ -1,17 +1,46 @@
 #!/usr/bin/env nix-shell
 #!nix-shell -i bash -p bash -p coreutils-full
 
-# redirects to $1, when writing to $1 requires sudo permissions.
-# i.e. convert a failing command:
-#
-# ```
-# $ sudo do_thing > /into/file
-# ```
-#
-# to
-#
-# ```
-# $ sudo do_thing | sane-sudo-redirect /into/file
-# ```
+set -eu
 
-exec sudo tee "$@" > /dev/null
+usage() {
+  echo 'sane-sudo-redirect COMMAND...'
+  echo
+  echo 'redirects to $1, when writing to $1 requires sudo permissions.'
+  echo 'i.e. convert a failing command:'
+  echo
+  echo '```'
+  echo '$ sudo do_thing > /into/file'
+  echo '```'
+  echo
+  echo 'to'
+  echo
+  echo '```'
+  echo '$ sudo do_thing | sane-sudo-redirect /into/file'
+  echo '```'
+}
+
+cmd=()
+parseArgs() {
+  while [ "$#" -ne 0 ]; do
+    local arg=$1
+    shift
+    if (( ${#cmd[@]} )); then
+      # all remaining arguments are to be forwarded to the subcommand
+      cmd+=("$arg")
+    else
+      case $arg in
+        (--help)
+          usage
+          exit 0
+          ;;
+        (*)
+          cmd=("$arg")
+          ;;
+      esac
+    fi
+  done
+}
+
+parseArgs "$@"
+exec sudo tee "${cmd[@]}" > /dev/null
diff --git a/repos/colinsane/scripts/deploy b/repos/colinsane/scripts/deploy
--- a/repos/colinsane/scripts/deploy
+++ b/repos/colinsane/scripts/deploy
@@ -4,6 +4,11 @@
 # TODO: simplify variant handling by defining `desko-full = desko`, etc, in nix config.
 
 const SELF = $(hostname)
+# which hosts to deploy to (in order), when "all hosts" is specified or implied.
+const ALL_HOSTS = [ "moby", "flowy", "desko", "servo" ]
+# which variants to build (in order), when "all variants" is specified or implied.
+const ALL_VARIANTS = ["-min", "-light", "", "-next-min", "-next-light", "-next"]
+
 
 # mutated by `main`
 var DRY_RUN = false
@@ -77,8 +82,7 @@ var NixConfig = Object(null, {
 # @return: list[str]
 func expandHostAlias (host) {
   if (host === "all" ) {
-    # order matters:
-    return (["moby", "lappy", "desko", "servo"])
+    return (ALL_HOSTS)
   } else {
     return ([host])
   }
@@ -88,7 +92,7 @@ func expandHostAlias (host) {
 # @return: list[str]
 func expandVariantAlias (v) {
   if (v === "all") {
-    return (["-min", "-light", "", "-next-min", "-next-light", "-next"])
+    return (ALL_VARIANTS)
   } elif (v === "") {
     # "full" variant
     return ([""])
@@ -169,14 +173,28 @@ func parseArgs(...args) {
   return (_parseArgs (p, ...args))
 }
 
-proc destructive (...cmd; ; echo=false) {
+proc invoke (...cmd; ; echo=false, translate_error=null) {
+  if (echo) {
+    echo @cmd >&2
+  }
+  if (translate_error !== null) {
+    try {
+      @cmd
+    }
+    if failed {
+      # `exit` from subshell so the exit code can be caught by an outer `try`
+      $(exit $translate_error)
+    }
+  } else {
+    @cmd
+  }
+}
+
+proc destructive (...cmd; ; echo=false, translate_error=null) {
   if (DRY_RUN) {
     info "dry-run:" (...cmd)
   } else {
-    if (echo) {
-      echo @cmd >&2
-    }
-    @cmd
+    invoke @cmd (echo=echo, translate_error=translate_error)
   }
 }
 
@@ -237,6 +255,26 @@ proc runOnTarget (host, ...cmd) {
   }
 }
 
+# `deployOneHost` exit codes:
+const FAILED_EVAL = 101
+const FAILED_BUILD = 102
+const FAILED_COPY = 103
+const FAILED_SET_PROFILE = 104
+const FAILED_ACTIVATE = 105
+const FAILED_REBOOT = 106
+
+func returnCodeToString (rc) {
+  case (rc) {
+    $FAILED_EVAL { return ("failed eval"); }
+    $FAILED_BUILD { return ("failed build"); }
+    $FAILED_COPY { return ("failed to copy the derivation"); }
+    $FAILED_SET_PROFILE { return ("failed to set the new profile as the next boot entry"); }
+    $FAILED_ACTIVATE { return ("failed to activate the new profile"); }
+    $FAILED_REBOOT { return ("failed to reboot target"); }
+    * { return ("unknown error: $rc"); }
+  }
+}
+
 proc deployOneHost (; nixcfg) {
   # unpack the cfg
   var timeout = timeoutFor(nixcfg.variant)
@@ -251,11 +289,13 @@ proc deployOneHost (; nixcfg) {
       # `nix-build -A foo` evals and then realizes foo, but it never unloads the memory used to eval foo.
       # my exprs are heavyweight, we need that memory for building, so do the evals separately from the realizations:
       info "$attrName: evaluating..."
-      setvar drvPath = $(nix eval --raw -f . "hosts.$attrName.toplevel.drvPath")
+      setvar drvPath = $(invoke nix eval --raw -f . "hosts.$attrName.toplevel.drvPath" (translate_error=FAILED_EVAL))
     }
 
     info "$attrName: building $drvPath"
-    setvar myStorePath = $(destructive nix-store --realize "$drvPath" @NIX_ARGS)
+    setvar myStorePath = $(destructive nix-store --realize "$drvPath" --add-root "./build/$attrName" @NIX_ARGS (translate_error=FAILED_BUILD))
+    # if using `nix-store --add-root`, then nix prints the gc root path, instead of the /nix/store path; resolve it
+    setvar myStorePath = $(realpath "$myStorePath")
     info "$attrName: built $myStorePath"
   }
 
@@ -275,39 +315,42 @@ proc deployOneHost (; nixcfg) {
       if (host !== SELF) {
         if test -e /run/secrets/nix_signing_key {
           info "signing store paths ..."
-          destructive sudo nix store sign -r -k /run/secrets/nix_signing_key "$myStorePath"
+          destructive sudo nix store sign -r -k /run/secrets/nix_signing_key "$myStorePath" (translate_error=FAILED_COPY)
         } else {
           info "not signing store paths: /run/secrets/nix_signing_key does not exist"
         }
         # add more `-v` for more verbosity (up to 5).
         # builders-use-substitutes false: optimizes so that the remote machine doesn't try to get paths from its substituters.
         #   we already have all paths here, and the remote substitution is slow to check and SERIOUSLY flaky on moby in particular.
-        destructive timeout "$timeout" nix copy -vv --option builders-use-substitutes false --to "ssh-ng://$netHost" "$myStorePath" (echo=true)
+        destructive timeout "$timeout" nix copy -vv --option builders-use-substitutes false --to "ssh-ng://$netHost" "$myStorePath" (echo=true, translate_error=FAILED_COPY)
       }
     }
   }
 
   case (nixcfg.action) {
     switch | test {
-      info "activating profile... "
-      destructive runOnTarget "$netHost" sudo nix-env -p /nix/var/nix/profiles/system --set "$myStorePath"
+      if (nixcfg.action === "switch") {
+        info "activating profile... "
+        destructive runOnTarget "$netHost" sudo nix-env -p /nix/var/nix/profiles/system --set "$myStorePath" (translate_error=FAILED_SET_PROFILE)
+      }
 
       # at this point, the new profile will be booted into on next boot.
       # try to switch to that profile _now_, but allow this to be fallible
       # so as to support `--force-reboot` CLI option:
       try {
-        destructive runOnTarget "$netHost" sudo "$myStorePath/bin/switch-to-configuration" "$[nixcfg.action]"
+        destructive runOnTarget "$netHost" sudo NIXOS_INSTALL_BOOTLOADER=1 "$myStorePath/bin/switch-to-configuration" "$[nixcfg.action]"
       }
-      var fail = false
-      if failed { setvar fail = true }  # XXX: `failed` special variable is only readable via `if failed`
+      var failed_activate = false
+      if failed { setvar failed_activate = true }  # XXX: `failed` special variable is only readable via `if failed`
 
-      if (nixcfg.reboot and (not fail or nixcfg.reboot === "force")) {
+      if (nixcfg.reboot and (not failed_activate or nixcfg.reboot === "force")) {
         info "$attrName: rebooting $host"
-        destructive runOnTarget "$netHost" sane-reboot "$host"
+        destructive runOnTarget "$netHost" sane-reboot "$host" (translate_error=FAILED_REBOOT)
       }
 
-      if (fail) {
-        false
+      if (failed_activate) {
+        # `exit` from subshell so the exit code can be caught by an outer `try`
+        $(exit $FAILED_ACTIVATE)
       }
     }
   }
@@ -394,8 +437,9 @@ proc main (...args) {
       deployOneHost (cfg)
     }
     if failed {
-      info "❌$[cfg.host]$[cfg.variant]: failed deployment!"
-      call failedDeploys->append(cfg)
+      var rc = _error.code
+      info "❌$[cfg.host]$[cfg.variant]: failed deployment: $[returnCodeToString (rc)]"
+      call failedDeploys->append({ cfg: cfg, rc: rc })
     } else {
       info "✅$[cfg.host]$[cfg.variant]: deployment complete"
     }
@@ -404,7 +448,7 @@ proc main (...args) {
   if (failedDeploys !== []) {
     echo "FAILED DEPLOYMENT:"
     for d in (failedDeploys) {
-      echo "- $[d.host]$[d.variant]"
+      echo "- $[d.cfg.host]$[d.cfg.variant]: $[returnCodeToString (d.rc)]"
     }
     exit 1
   }
diff --git a/repos/colinsane/scripts/sync b/repos/colinsane/scripts/sync
--- a/repos/colinsane/scripts/sync
+++ b/repos/colinsane/scripts/sync
@@ -1,173 +1,275 @@
 #!/usr/bin/env nix-shell
-#!nix-shell -i bash -p bash -p rsync -p sane-scripts.sync-from-iphone -p sane-scripts.sync-music
+#!nix-shell -i ysh -p oils-for-unix -p rsync -p sane-scripts.sync-from-iphone -p sane-scripts.sync-music
 
-usage() {
-  echo "sync [flags ...] [<host> [<host> ...]] [passthrough flags ...]"
+# mutated by `main`
+var DRY_RUN = false
+var VERBOSITY = 0
+
+proc usage {
+  echo "sync [--dry-run --verbose] [<host|target> [<host|target> ...]] [passthrough flags ...]"
   echo "where:"
-  echo "  host: all|desko|lappy|moby"
+  echo "  host: all|desko|flowy|moby"
   echo "  - defaults to 'all' if omitted"
+  echo "  target: pkm|music|books|photos"
+  echo "  - defaults to all if omitted"
+  echo ""
+  echo "ENVIRONMENT VARIABLES:"
+  echo "- SYNC_DEBUG=$VERBOSITY"
+}
+
+func verboseFlag(flags = null) {
+  if (flags === null) {
+    setvar flags = ["--verbose"]
+  }
+
+  if (VERBOSITY >= 1) {
+    return (flags)
+  } else {
+    return ([])
+  }
+}
+
+func verboseRsyncFlag() {
+  return (verboseFlag(["--verbose", "--progress"]))
+}
+
+proc debug (...plain) {
+  if (VERBOSITY >= 1) {
+    echo "[debg]" @plain
+  }
+}
+
+proc verbose (...plain) {
+  if (VERBOSITY >= 2) {
+    echo "[verb]" @plain
+  }
+}
+
+proc effect (...args) {
+  if (DRY_RUN) {
+    echo "[dry ]" @args
+  } else {
+    verbose @args
+    @args
+  }
+}
+
+proc die (...msg) {
+  echo "[fatal]" @msg
   exit 1
 }
 
-debug() {
-  if [ -n "$SYNC_DEBUG" ]; then
-    echo "$@"
-  fi
-}
-
-ifExists() {
-  local path="$1"
-  shift
-  local cmd="$@"
-  if test -d "$path"; then
-    debug "${cmd[@]}"
-    ${cmd[@]}
-  else
+proc ifExists (path, ...cmd) {
+  verbose "ifExists $path ..."
+  if test -d "$path" {
+    debug @cmd
+    @cmd
+  } else {
     debug "skipping action because $path doesn't exist"
-  fi
+  }
 }
 
-homeMountFor() {
-  local want=$1
-  local me=$(hostname)
-  if [ "$want" = "$me" ]; then
-    echo "$HOME"
-  else
-    echo "/mnt/$want/home"
-  fi
+func homeMountFor (want) {
+  var me = $(hostname)
+  if (want === me) {
+    return (ENV.HOME)
+  } else {
+    return ("/mnt/$want/home")
+  }
 }
 
-sync_pkm() {
-  local host=$1
-  local me=$(hostname)
-  if [ "$host" != "$me" ]; then
-    ssh "$host" "set -eux; remote=$me; "'cd ~/knowledge; old=$(git rev-parse --abbrev-ref HEAD); [ "$old" = master ]; st=$(git stash create); git reset --hard HEAD; git branch -D sync || true; git checkout -b sync; git fetch $remote master && git rebase $remote/master && (if [ -n "$st" ]; then git stash apply "$st"; fi) && git branch --move --force master || (git --reset-hard HEAD; git checkout "$old"; (if [ -n "$st" ]; then git stash apply "$st"; fi); false)'
-  fi
+proc sync_pkm (; host, passthruArgs) {
+  var me = $(hostname)
+  if (host !== me) {
+    ssh "$host" """\
+      # source profile to fix XDG_RUNTIME_DIR, necessary for ssh-agent to not break
+      source ~/.profile \
+      set -eux; \
+      remote=$me; \
+      cd ~/knowledge; \
+      old=\$(git rev-parse --abbrev-ref HEAD); \
+      [ "\$old" = master ]; \
+      st=\$(git stash create); \
+      git reset --hard HEAD; \
+      git branch -D sync || true; \
+      git checkout -b sync; \
+      git fetch \$remote master && git rebase \$remote/master && ( \
+        if [ -n "\$st" ]; then \
+          git stash apply "\$st"; \
+        fi \
+      ) && git branch --move --force master || ( \
+        git reset --hard HEAD; \
+        git checkout "\$old"; \
+        (if [ -n "\$st" ]; then git stash apply "\$st"; fi); \
+        false \
+      ) \
+    """
+  }
 }
 
-sync_music() {
-  local host=$1
-  shift
-  local deskoHome=$(homeMountFor desko)
-  local flowyHome=$(homeMountFor flowy)
-  local lappyHome=$(homeMountFor lappy)
-  local mobyHome=$(homeMountFor moby)
-  case $host in
-    (desko)
+proc sync_music (; host, passthruArgs) {
+  var deskoHome = homeMountFor ("desko")
+  var flowyHome = homeMountFor ("flowy")
+  var mobyHome = homeMountFor ("moby")
+
+  var verb = verboseFlag ()
+
+  case (host) {
+    "desko" {
       ifExists /mnt/servo/media/Music/Various.Artists \
-        sane-sync-music --compat /mnt/servo/media/Music "$deskoHome/Music" "$@"
-      ;;
-    (flowy)
+        effect sane-sync-music @verb --compat /mnt/servo/media/Music "$deskoHome/Music" @passthruArgs
+    }
+    "flowy" {
       ifExists /mnt/servo/media/Music/Various.Artists \
-        sane-sync-music --compat /mnt/servo/media/Music "$flowyHome/Music" "${syncFlags[@]}"
-      ;;
-    (lappy)
+        effect sane-sync-music @verb --compat /mnt/servo/media/Music "$flowyHome/Music" @passthruArgs
+    }
+    "moby" {
       ifExists /mnt/servo/media/Music/Various.Artists \
-        sane-sync-music --compress --compat /mnt/servo/media/Music "$lappyHome/Music" "${syncFlags[@]}"
-      ;;
-    (moby)
-      ifExists /mnt/servo/media/Music/Various.Artists \
-        sane-sync-music --compat /mnt/servo/media/Music "$mobyHome/Music" "${syncFlags[@]}"
-      ;;
-    (*)
-      ;;
-  esac
+        effect sane-sync-music @verb --compat /mnt/servo/media/Music "$mobyHome/Music" @passthruArgs
+    }
+    (else) {
+      die "unknown host $host"
+    }
+  }
 }
 
-sync_books() {
-  local host="$1"
-  local deskoHome=$(homeMountFor desko)
-  local lappyHome=$(homeMountFor lappy)
-  local flowyHome=$(homeMountFor flowy)
-  local mobyHome=$(homeMountFor moby)
-  case $host in
-    (moby)
+proc sync_books (; host, passthruArgs) {
+  var deskoHome = homeMountFor ("desko")
+  var flowyHome = homeMountFor ("flowy")
+  var mobyHome = homeMountFor ("moby")
+
+  var verb = verboseRsyncFlag ()
+
+  case (host) {
+    "moby" {
       ifExists /mnt/servo/media/Books/Audiobooks \
-        rsync -arv --delete /mnt/servo/media/Books/Audiobooks/ "$mobyHome/Books/Audiobooks/"
+        effect rsync @verb -ar --delete /mnt/servo/media/Books/Audiobooks/ "$mobyHome/Books/Audiobooks/"
       # copy books from servo to moby; delete old/untracked ones, but keep KOreader state files (sdr)
       ifExists /mnt/servo/media/Books/Books \
-        rsync -arv --delete --exclude '*.sdr' /mnt/servo/media/Books/Books/ "$mobyHome/Books/Books/"
+        effect rsync @verb -ar --delete --exclude '*.sdr' /mnt/servo/media/Books/Books/ "$mobyHome/Books/Books/"
       ifExists /mnt/servo/media/Books/Visual \
-        rsync -arv --delete --exclude '*.sdr' /mnt/servo/media/Books/Visual/ "$mobyHome/Books/Visual/"
-      ;;
-    (*)
-      ;;
-  esac
+        effect rsync @verb -ar --delete --exclude '*.sdr' /mnt/servo/media/Books/Visual/ "$mobyHome/Books/Visual/"
+    }
+    "desko" | "flowy" {
+      debug "noop"
+    }
+    (else) {
+      die "unknown host $host"
+    }
+  }
 }
 
-sync_photos() {
-  local host=$1
-  local deskoHome=$(homeMountFor desko)
-  local lappyHome=$(homeMountFor lappy)
-  local flowyHome=$(homeMountFor flowy)
-  local mobyHome=$(homeMountFor moby)
-  case $host in
-    (desko)
-      sane-sync-from-iphone
-      ;;
-    (moby)
+proc sync_photos (; host, passthruArgs) {
+  var deskoHome = homeMountFor ("desko")
+  var flowyHome = homeMountFor ("flowy")
+  var mobyHome = homeMountFor ("moby")
+
+  var verb = verboseRsyncFlag ()
+
+  case (host) {
+    "desko" {
+      sane-sync-from-iphone @commonArgs
+    }
+    "flowy" {
+      debug "noop"
+    }
+    "moby" {
       # copy photos/screenshots from moby to desko:
-      rsync -arv --exclude servo-macros "$mobyHome/Pictures/" "$deskoHome/Pictures/from/moby/"
-      ;;
-    (*)
-      ;;
-  esac
+      effect rsync @verb -ar --exclude servo-macros "$mobyHome/Pictures/" "$deskoHome/Pictures/from/moby/"
+    }
+    (else) {
+      die "unknown host $host"
+    }
+  }
 }
 
-hosts=()
-targets=()
-passthruArgs=()
-parseArgs() {
-  while [[ $# -ge 1 ]]; do
-    local arg=$1
-    case $arg in
-      (desko|flowy|lappy|moby)
-        hosts+=("$arg")
-        shift
-        ;;
-      (all)
-        hosts+=(desko flowy lappy moby)
-        shift
-        ;;
-      (pkm|music|books|photos)
-        targets+=("$arg")
-        shift
-        ;;
-      (--verbose)
-        if [[ "${#hosts[@]}" -eq 0 ]]; then
-          SYNC_DEBUG=1
-          shift
-        else
-          # it's a passthru flag
-          break
-        fi
-        ;;
-      (--help)
-        usage
-        shift
-        ;;
-      (*)
-        break
-        ;;
-    esac
-  done
-
-  passthruArgs+=("$@")
-
-  if [[ ${#hosts[@]} -eq 0 ]]; then
-    hosts+=(desko flowy lappy moby)
-  fi
-
-  if [[ ${#targets[@]} -eq 0 ]]; then
-    targets+=(pkm music photos books)
-  fi
+proc sync (; what, host, passthruArgs) {
+  debug "sync $what -> $host"
+  try {
+    case (what) {
+      "books" {
+        sync_books (host, passthruArgs)
+      }
+      "photos" {
+        sync_photos (host, passthruArgs)
+      }
+      "pkm" {
+        sync_pkm (host, passthruArgs)
+      }
+      "music" {
+        sync_music (host, passthruArgs)
+      }
+      (else) {
+        die "unknown sync target: $what"
+      }
+    }
+  }
+  if failed {
+    echo "FAILED TO SYNC $what -> $host"
+  }
 }
 
-parseArgs "$@"
-debug "hosts:" "${hosts[@]}"
-debug "targets:" "${targets[@]}"
-for target in "${targets[@]}"; do
-  for host in "${hosts[@]}"; do
-    sync_"$target" "$host" "${passthruArgs[@]}"
-  done
-done
+var hosts = []
+var targets = []
+var passthruArgs = []
+proc parseArgs (...args) {
+  for arg in (args) {
+    if (passthruArgs !== []) {
+      call passthruArgs->append(arg)
+    } else {
+      case (arg) {
+        "desko" | "flowy" | "moby" {
+          call hosts->append (arg)
+        }
+        "all" {
+          call hosts->extend ([desko, flowy, moby])
+        }
+        "pkm" | "music" | "books" | "photos" {
+          call targets->append (arg)
+        }
+        "--dry-run" {
+          setglobal DRY_RUN = true
+        }
+        "-h" | "--help" {
+          usage
+          exit 0
+        }
+        "-v" | "--verbose" {
+          setglobal VERBOSITY += 1
+        }
+        (else) {
+          call passthruArgs->append(arg)
+        }
+      }
+    }
+  }
+
+  var env_verbosity = get(ENV, "SYNC_DEBUG")
+  if (env_verbosity !== null) {
+    try {
+      setglobal VERBOSITY = int(env_verbosity)
+    }
+    if failed {
+      if (env_verbosity !== "") {
+        setglobal VERBOSITY += 1
+      }
+    }
+  }
+
+  if (hosts === []) {
+    call hosts->extend(["desko", "flowy", "moby"])
+  }
+
+  if (targets === []) {
+    call targets->extend(["pkm", "music", "photos", "books"])
+  }
+}
+
+parseArgs @ARGV
+debug "hosts:" @hosts
+debug "targets:" @targets
+for target in (targets) {
+  for host in (hosts) {
+    sync (target, host, passthruArgs)
+  }
+}
