meain: 73280fb4a3 -> 63ed21099f

diff --git a/repos/meain/_scripts/autoupdate b/repos/meain/_scripts/autoupdate
--- a/repos/meain/_scripts/autoupdate
+++ b/repos/meain/_scripts/autoupdate
@@ -10,10 +10,11 @@ skipupdate=0
 
 [ -z "$1" ] && echo "Pass in package name" && exit 1
 package="$1"
-file="pkgs/$package/default.nix"
+folder="$(echo "$1" | awk -F'.' '{print $NF}')"
+file="pkgs/$folder/default.nix"
 
 printf "\n\n[] updating %s\n" "$package"
-if ! grep -q 'fetchFromGitHub' "$file"; then
+if ! grep -q 'github.com' "$file"; then
 	echo "We don't really know how to update this as the source is not from Github"
 	exit 1
 fi
@@ -28,7 +29,7 @@ if [ "$skipupdate" -ne 1 ]; then
 	release_url="$(echo $github_url | sed 's|github.com|api.github.com/repos|;s|$|/releases/latest|')"
 	cversion="$(grep -E "version[^=]*=[^\"]*\"[^\"]*\"" "$file" | sed "s|.*version[^=]*=[^\"]*\"\([^\"]*\)\".*|\1|")"
 	lversion="$(curl --silent "$release_url" | tee /tmp/autoupdate-curl | jq -er .tag_name | sed 's/^[vV]//')"
-    [ "$lversion" = "null" ] && echo "Unable to fetch latest version" && exit 1
+	[ "$lversion" = "null" ] && echo "Unable to fetch latest version" && exit 1
 	echo Current: "$cversion" '|' Latest: $lversion
 	if [ "$lversion" = "$cversion" ]; then
 		echo "Already on latest release, not upgrading" && exit 0
@@ -42,10 +43,14 @@ sed -i 's|"sha256[:-][^"]*"|lib.fakeSha256|' "$file"
 while ! nix-build -A "$package" 2>/tmp/nix-build-log; do
 	newsha="$(grep "            got:    sha256-" /tmp/nix-build-log | awk -F' ' '{print $NF}')"
 	echo "- using: $newsha"
-    [ -z $newsha ] && exit 1
+	[ -z $newsha ] && exit 1
 	sed -i "0,/lib.fakeSha256/s|lib.fakeSha256|\"$newsha\"|1" "$file"
 done
 
 git config --global user.email "bot@meain.io"
 git config --global user.name "Bot"
-git add "pkgs/$package" && git commit -m "$package: $cversion -> $lversion"
+if [ "$skipupdate" -ne 1 ]; then
+	git add "pkgs/$folder" && git commit -m "$package: $cversion -> $lversion"
+else
+	git add "pkgs/$folder" && git commit -m "$package: recompute"
+fi
